class-attrs-all:
  pre-cluster-threshold: 0.5
property:
  gie-unique-id: 1
  cluster-mode: 4
  data-format: channels_first
  infer-dims: 3;640;640
  maintain-aspect-ratio: 1
  model-color-format: 0  # RGB
  net-scale-factor: 0.00392156863 # 1 / (255 x 1)
  network-mode: 2  # 0 FP32, 2 FP16
  network-type: 0
  num-detected-classes: 80
  onnx-file: model.onnx
  model-engine-file: ./model.onnx_b1_gpu0_fp16.engine
  labelfile-path: ./labels.txt
  parse-bbox-func-name: NvDsInferParseCustomDDETRTAO
  custom-lib-path: /opt/nvidia/deepstream/deepstream/lib/libnvds_infercustomparser_tao.so
  workspace-size: 1048576
  # scaling-filter: 2 # 2 cubic
