services:
  tao-cv:
    image: gitlab-master.nvidia.com:5005/deepstreamsdk/inference-builder/cv-tao-common:rc0
    volumes:
      - '~/.cache/nim:/opt/nim/.cache'
      - './validation/rtdetr/model_manifest.yaml:/opt/nim/etc/default/model_manifest.yaml:ro'
    ipc: host
    # init: true
    ports:
      - "8800-8803:8000-8003"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: 1
              device_ids: ['0']
              capabilities: [gpu]
    environment:
      DEBUG: 1
      NIM_MODEL_NAME: rtdetr