property:
  cluster-mode: 4
  gie-unique-id: 1
  infer-dims: 3;224;224
  maintain-aspect-ratio: 1
  net-scale-factor: 0.0173520735728
  network-mode: 1
  network-type: 1 # classification
  # num-detected-classes: 19
  onnx-file: classifier.onnx
  model-engine-file: ./classifier.onnx_b1_gpu0_fp16.engine
  output-blob-names: output
  # output-tensor-meta: 1
  workspace-size: 1048576
  classifier-threshold: 0.5
  labelfile-path: ./labels.txt
