property:
  tensor-name: inputs
  processing-width: 960
  processing-height: 544
  network-input-shape: 1;3;544;960
  network-color-format: 0
  network-input-order: 0
  tensor-data-type: 0
  maintain-aspect-ratio: 1
  symmetric-padding: 1
  scaling-pool-memory-type: 0
  scaling-pool-compute-hw: 0
  scaling-filter: 0
  scaling-buf-pool-size: 6
  tensor-buf-pool-size: 6
  target-unique-ids: 1
  process-on-frame: 1
  unique-id: 5
  custom-lib-path: /opt/nvidia/deepstream/deepstream/lib/gst-plugins/libcustom2d_preprocess.so
  custom-tensor-preparation-function: CustomTensorPreparation
  enable: 1
user-configs:
  pixel-normalization-factor: 0.007843137
  offsets: 127.5;127.5;127.5
group:
  - src-ids: -1
    custom-input-transformation-function: CustomAsyncTransformation
    process-on-roi: 0

