# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

# The values in the config file are overridden by values set through GObject properties.

property:
  tensor-name: inputs
  processing-width: 960
  processing-height: 544
  network-input-shape: 1;3;544;960
  # Color format (0=RGB, 1=BGR, 2=GRAY)
  network-color-format: 0

  # Network input order (0=NCHW, 1=NHWC, 2=CUSTOM)
  network-input-order: 0
  # Tensor data type (0=FP32, 1=UINT8, 2=INT8, 3=UINT32, 4=INT32, 5=FP16)
  tensor-data-type: 0
  # Maintain aspect ratio while scaling
  maintain-aspect-ratio: 1
  # Pad symmetrically with maintain-aspect-ratio enabled
  symmetric-padding: 1
  # Memory type (0=NVBUF_MEM_DEFAULT, 1=NVBUF_MEM_CUDA_PINNED, 2=NVBUF_MEM_CUDA_DEVICE, 3=NVBUF_MEM_CUDA_UNIFIED)
  scaling-pool-memory-type: 0
  # Compute hardware (0=Default, 1=GPU, 2=VIC)
  scaling-pool-compute-hw: 0
  # Scaling interpolation method
  # 0=Nearest, 1=Bilinear, 2=Algo1, 3=Algo2, 4=Algo3, 5=Algo4, 6=Default
  scaling-filter: 0
  scaling-buf-pool-size: 6
  tensor-buf-pool-size: 6
  # List of component gie-id for which tensor is prepared
  target-unique-ids: 1
  # Process type (0=process on objects, 1=process on frames)
  process-on-frame: 1
  # Uniquely identify the metadata generated by this element
  unique-id: 5
  # Custom library configuration
  custom-lib-path: /opt/nvidia/deepstream/deepstream/lib/gst-plugins/libcustom2d_preprocess.so
  custom-tensor-preparation-function: CustomTensorPreparation
  # Enable the component
  enable: 1
user-configs:
  # Network scaling factor
  pixel-normalization-factor: 0.007843137
  # Channel offsets
  offsets: 127.5;127.5;127.5
group:
  - src-ids: -1
    custom-input-transformation-function: CustomAsyncTransformation
    process-on-roi: 0

