# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# inference-builder/deploy/.gitlab-ci.deploy.yml

.deploy_workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH || $CI_COMMIT_TAG'
      when: always

# Template for deployment test using Helm
.deploy_test_template: &deploy_test_template
  stage: deploy-test
  image: $DEPLOYER_IMAGE
  variables:
    KUBECONFIG: "${CI_PROJECT_DIR}/kubeconfig"
  script:
    - echo "Running tests on deployment host..."
    - python3 deploy/remote_deploy.py --mode test
  artifacts:
    when: always  # Save artifacts even if job fails
    paths:
      - builder/samples/tao/helm/charts/    # Save downloaded chart
      - builder/samples/tao/helm/tao-cv-app/  # Save modified values
    expire_in: 1 week
  rules:
    - when: manual   # Always allow manual trigger
  allow_failure: false  # This makes the job optional for pipeline success

# Deployment test jobs for each flavor
deploy_test_common:
  <<: *deploy_test_template
  variables:
    FLAVOR: "tao"
  dependencies:
    - build_docker_common_nim
  needs:
    - build_docker_common_nim
  rules:
    - if: '$CI_JOB_TRIGGERED_BY =~ /build_docker_common_nim/'
      when: always  # Must run after build_docker_common_nim
    - when: manual  # Also allow manual trigger

deploy_test_changenet:
  <<: *deploy_test_template
  variables:
    FLAVOR: "changenet"
  dependencies:
    - build_docker_changenet_nim
  needs:
    - build_docker_changenet_nim
  rules:
    - if: '$CI_JOB_TRIGGERED_BY =~ /build_docker_changenet_nim/'
      when: always  # Must run after build_docker_changenet_nim
    - when: manual  # Also allow manual trigger

deploy_test_gdino:
  <<: *deploy_test_template
  variables:
    FLAVOR: "gdino"
  dependencies:
    - build_docker_gdino_nim
  needs:
    - build_docker_gdino_nim
  rules:
    - if: '$CI_JOB_TRIGGERED_BY =~ /build_docker_gdino_nim/'
      when: always  # Must run after build_docker_gdino_nim
    - when: manual  # Also allow manual trigger


# Single deployment using Helm
deploy_with_config:
  stage: deploy
  image: $DEPLOYER_IMAGE
  variables:
    FLAVOR: "tao"
    MODEL_TYPE: "rtdetr"
    KUBECONFIG: "${CI_PROJECT_DIR}/kubeconfig"
  script:
    # Check all required variables at once
    - |
      for var in FLAVOR MODEL_TYPE OVERRIDE_IMAGE; do
        if [ -z "${!var}" ]; then
          echo "Error: $var is not set. Please configure it as onetime CI/CD variables for this job."
          exit 1
        fi
      done
    - echo "Triggering deployment for ${FLAVOR}/${MODEL_TYPE} with ${OVERRIDE_IMAGE}..."
    - python3 deploy/remote_deploy.py --mode deploy --flavor ${FLAVOR} --model-type ${MODEL_TYPE}
  artifacts:
    when: always  # Save artifacts even if job fails
    paths:
      - builder/samples/tao/helm/charts/    # Save downloaded chart
      - builder/samples/tao/helm/tao-cv-app/  # Save modified values
    expire_in: 1 week
  rules:
    - when: manual   # Always allow manual trigger
  allow_failure: true  # This makes the job optional for pipeline success
