%YAML:1.0

BaseConfig:
  debugVerboseLevel: 1
  minDetectorConfidence: 0.027087304322979212
TargetManagement:
  debugVerboseLevel: 0
  enableBboxUnClipping: 1
  preserveStreamUpdateOrder: 0
  maxTargetsPerStream: 200
  minIouDiff4NewTarget: 0.22656630527418112
  minTrackerConfidence: 0.6957540479571296
  probationAge: 1
  maxShadowTrackingAge: 162
  earlyTerminationAge: 1
  maxTrajectoryBufferLength: -1
  outputTerminatedTracks: 0
TrajectoryManagement:
  debugVerboseLevel: 0
  useUniqueID: 0
  enableReAssoc: 1
  minMatchingScore4Overall: 0.9349462651721144
  minTrackletMatchingScore: 0.2940
  minMatchingScore4ReidSimilarity: 0
  matchingScoreWeight4TrackletSimilarity: 0.7981
  matchingScoreWeight4ReidSimilarity: 0
  minTrajectoryLength4Projection: 34
  prepLength4TrajectoryProjection: 58
  trajectoryProjectionLength: 33
  maxAngle4TrackletMatching: 67
  minSpeedSimilarity4TrackletMatching: 0.0574
  minBboxSizeSimilarity4TrackletMatching: 0.1013
  minMatchRatio4ValidTrackletDetermination: 0.0000
  maxTrackletMatchingTimeSearchRange: 27
  trajectoryProjectionProcessNoiseScale: 0.0100
  trajectoryProjectionMeasurementNoiseScale: 100
  trackletSpacialSearchRegionScale: 0.0100
  reidExtractionInterval: 0
  dumpTrajectoryIntoFile: 1
  dumpDetectorBboxes: 1
  dumpTrajectoryTentative: 1
  dumpTrajectoryQuasiActive: 0
  dumpTrajectoryInactive: 0
  minVisibility4TrajDump: 0.0000
  trajectoryDumpFileName: /workspace/models/PeopleNetTransformer/trajDumps/trajDump_Stream_
DataAssociator:
  dataAssociatorType: 0
  associationMatcherType: 1
  checkClassMatch: 0
  minMatchingScore4Overall: 0.6671945991661751
  minMatchingScore4SizeSimilarity: 0.6718623956657859
  minMatchingScore4Iou: 0.1393522182207021
  minMatchingScore4VisualSimilarity: 0.0520394823204932
  matchingScoreWeight4SizeSimilarity: 0.104589699500018
  matchingScoreWeight4Iou: 0.7844652139368062
  matchingScoreWeight4VisualSimilarity: 0.9294872869302965
  tentativeDetectorConfidence: 0.70167245554449
  minMatchingScore4TentativeIou: 0.1768733030811293
  minMatchingScore4PeerAssocIou: 0.2
StateEstimator:
  stateEstimatorType: 3
  processNoiseVar4Loc: 6497.75224242603
  processNoiseVar4Vel: 8035.858212054732
  measurementNoiseVar4Detector: 100.0000
  measurementNoiseVar4Tracker: 883.5847350922555
ObjectModelProjection:
  outputFootLocation: 1
  outputVisibility: 1
  outputConvexHull: 0
  cameraModelFilepath:  # In order of the source streams (absolute or relative) # TODO: the default name can be more general  
    - /workspace/inputs/camInfo/Warehouse_Synthetic_Cam001.yml
    - /workspace/inputs/camInfo/Warehouse_Synthetic_Cam002.yml
    - /workspace/inputs/camInfo/Warehouse_Synthetic_Cam003.yml
    - /workspace/inputs/camInfo/Warehouse_Synthetic_Cam004.yml
  objectModelType: 0
VisualTracker:
  visualTrackerType: 1
  useColorNames: 1
  useHog: 1
  featureImgSizeLevel: 5
  featureFocusOffsetFactor_y: -0.10525549278780495
  filterLr: 0.025008995723548734
  filterChannelWeightsLr: 0.09460260509799209
  gaussianSigma: 0.44967391866177786
  # visualization:
  #   vizWriteSrcImgPatchesAndCorrResp: 0
  #   vizWriteBirdsEyeView: 0
  #   vizWriteAllTrajectoriesOnEveryFrame: 1
  #   vizWriteEachCompletedTrajectory: 0
  #   vizJpegImageQuality: 25 #25
  #   vizOutDirectory: "trackerViz"
  #   vizDebugStreamId: -1
ReID:
  reidType: 0
  batchSize: 100
  workspaceSize: 1000
  reidFeatureSize: 256
  reidHistorySize: 100
  inferDims: [3, 256, 128]
  networkMode: 1
  inputOrder: 0
  colorFormat: 0
  offsets: [123.6750, 116.2800, 103.5300]
  netScaleFactor: 0.01735207
  keepAspc: 1
  addFeatureNormalization: 1
  modelEngineFile: /workspace/models/ReID-MTMC/resnet50_market1501.etlt_b100_gpu0_fp16.engine
  tltEncodedModel: /workspace/models/ReID-MTMC/resnet50_market1501.etlt
  tltModelKey: nvidia_tao
MultiViewAssociator:
  debugVerboseLevel: 2
  multiViewAssociatorType: 1
  minPeerToPredDistance4Fusion: 4.0 # mtmc 4.0 # 1.0 # sdg 1.3475168402461755
  minPeerTrackletMatchScore: 0.3 # mtmc 0.3 # sdg 0.48 # 0.48177346044415703
  minPeerVisibility4Fusion: 0.15 # sdg 0.1575362440818593
  recentlyActiveAge: 178
Communicator:
  communicatorType: 2 # 0: no communicator, 1: mqtt communicator
  pubSubInfoConfigPath: /workspace/models/PeopleNetTransformer/pub_sub_info_config_0.yml
  debugVerboseLevel: 1 # verbose level among { 0: warnings and errors, 1: detailed info}
  saveLog2File: 1 # whether to save communication contents to file for debugging, {0: not save, 1: save}
  mqttProtoAdaptorConfigPath: /workspace/models/PeopleNetTransformer/config_mqtt.txt
  connTimeout: 200
  waitForConnInterval: 10
PoseEstimator:
  poseEstimatorType: 1
  batchSize: 1
  workspaceSize: 1000
  inferDims: [3, 256, 192]
  networkMode: 1
  inputOrder: 0
  colorFormat: 1
  offsets: [123.6750, 116.2800, 103.5300]
  netScaleFactor: 0.00392156
  tltEncodedModel: /workspace/models/BodyPose3DNet/bodypose3dnet_accuracy.etlt
  modelEngineFile: /workspace/models/BodyPose3DNet/bodypose3dnet_accuracy.etlt_b1_gpu0_fp16.engine
  tltModelKey: tlt_encode
  poseInferenceInterval: -1
  saveFrameViz: 0