# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# inference-builder/builder/samples/tao/validation/.gitlab-ci.validation.yml

.validation_workflow:
  rules:
    - changes:
        - "builder/samples/tao/validation/**/*"  # Full path from repo root
      when: always
    - when: never

build_validation_context:
  extends: .validation_workflow
  stage: build-validator
  image: $BUILDER_IMAGE
  script:
    # Still need to cd from repo root
    - cd builder/samples/tao/validation
    - NO_DOCKER=true python build.py
    # Check if .tmp directories exist and are not empty
    - |
      echo "Checking .tmp directories..."
      empty_dirs=0
      for model in */; do
        if [ ! -d "${model}.tmp" ] || [ -z "$(ls -A ${model}.tmp)" ]; then
          echo "Error: ${model}.tmp is empty or missing"
          empty_dirs=1
        else
          echo "✓ ${model}.tmp exists and contains files"
          ls -la "${model}.tmp"
        fi
      done
      if [ $empty_dirs -eq 1 ]; then
        echo "ERROR: Some .tmp directories are empty or missing"
        exit 1
      fi
  artifacts:
    paths:
      # Need full path from repo root
      - builder/samples/tao/validation/*/.tmp/
    expire_in: 1 hour

build_validation_container:
  extends: .validation_workflow
  stage: build-validator
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  needs:
    - build_validation_context
  dependencies:
    - build_validation_context  # Add this to get the artifacts
  script:
    # Verify artifacts before building
    - |
      echo "Verifying .tmp directories..."
      empty_dirs=0
      cd builder/samples/tao/validation
      for model in */; do
        if [ ! -d "${model}.tmp" ] || [ -z "$(ls -A ${model}.tmp)" ]; then
          echo "Error: ${model}.tmp is empty or missing"
          empty_dirs=1
        else
          echo "✓ ${model}.tmp exists and contains files"
          ls -la "${model}.tmp"
        fi
      done
      if [ $empty_dirs -eq 1 ]; then
        echo "ERROR: Some .tmp directories are empty or missing"
        exit 1
      fi
    # Continue with build if checks pass
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    # Still need to cd from repo root
    # - cd builder/samples/tao/validation  # already in Verify artifacts above
    - docker compose build validation-client
    - docker tag validation-client ${CI_REGISTRY_IMAGE}/cv-tao-validation:${CI_COMMIT_SHA}
    - docker push ${CI_REGISTRY_IMAGE}/cv-tao-validation:${CI_COMMIT_SHA}