# Copyright (c) 2022-2023, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

type: msapplication
specVersion: 2.5.0
name: ucf.svc.tao-cv
chartName: tao-cv
description: TAO CV MS
version: 0.0.1
displayName: ""
category:
  functional: ""
  industry: ""
tags: []
keywords: []
nSpectId: NSPECT-0000-0000

publish: false

ingress-endpoints:
  - name: http-api
    description: http inference endpoint
    scheme: http
    data-flow: in-out # Or in or out

params:
  modelName: rtdetr
  #> type: string
  #> enum_values: dino, classifier, segformer, rtdetr 
  #> description: Use TaskHead model name to categorize the models that have the same output layout

# tests:
#   - name: dev-params1
#     app: tests/dev/app.yaml
#     params: tests/dev/params1.yaml
#     ciTrigger: false
#     timeout: 10
#     duration: 10
#     installPreReqs: true  # Wether to install foundational services
#     namespace: default  # Kubernetes namespace
#     gpuNodeLabels: ""
#     watchAllPods: true # OR set to false and set list of pods to watch below
#     watchPods:
#     - <pod-name-regex>
#     testerPods:  # At least one tester pod is required
#     - name: testpod1  # Name of the test pod
#       startSignature: <START>  # Signature to look for in the logs indicating start of tests. Regex is accepted
#       endSignature: <END>  # Signature to look for in the logs indicating end of tests. Regex is accepted
#       errorSignatures:  # Signatures that indicate test failures.  Regex is accepted
#       - <REGEX1>
#       - <REGEX2>

---
spec:
  - name: tao-cv-deployment
    type: ucf.k8s.app.deployment
    parameters:
      apptype: stateless

  - name: "tao-cv-container"
    type: ucf.k8s.container
    parameters:
      image:
        # repository: gitlab-master.nvidia.com:5005/deepstreamsdk/inference-builder/cv-tao-tao
        # repository: nvcr.io/eevaigoeixww/staging/tao_cv_nim
        repository: gitlab-master.nvidia.com:5005/deepstreamsdk/inference-builder/cv-tao-tao
        tag: "20250423.test.2"
      command: [bash, /opt/scripts/start.sh]
      # command: ["sleep", "infinity"]
      env:
      - name: NGC_API_KEY
        valueFrom:
          secretKeyRef:
            name: ngc-secret
            key: ngc-api-key
      - name: NIM_MODEL_NAME
        value: $params.modelName
      ports:
      - containerPort: 8000 # <PORT>
        name: http
      volumeMounts:
        - name: localvol
          mountPath: /opt/nim/.cache
      startupProbe:
        httpGet:
          path: /v1/health/ready
          port: http
        failureThreshold: 30
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /v1/health/live
          port: http
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 20
        failureThreshold: 3


  - name: podSecurityContext
    type: ucf.k8s.podSecurityContext
    parameters:
      runAsGroup: 1000
      runAsUser: 1000

  - name: tao-cv-service
    type: ucf.k8s.service
    parameters:
      ports:
      - port: 8000  # <OUT_PORT>
        name: http-api
        targetPort: 8000

  # - name: tao-cv-service
  #   type: ucf.k8s.service
  #   parameters:
  #     type: NodePort
  #     ports:
  #     - port: 8000 # <OUT_PORT>
  #       name: http-api
  #       targetPort: 8000
  #       nodePort: 30080
  #     externalTrafficPolicy: Local # Cluster / Local. Allowed when service type is NodePort or LoadBalancer

  - name: localvol
    type: ucf.k8s.volume
    parameters:
      persistentVolumeClaim:
        claimName: tao-cv-ngc-model-cache-pvc

  - name: ngc-model-cache-pvc
    type: ucf.k8s.pvc
    parameters:
      annotations:
        helm.sh/resource-policy: "keep"
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 10Gi

  - name: ngc-image-pull-secret
    type: ucf.k8s.imagepullsecret
    parameters:
      name: ngc-docker-reg-secret
      
